name: Render Quarto to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true

    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: scheme-basic

    - name: Install Japanese Fonts
      run: |
        tlmgr install collection-langjapanese
        tlmgr install haranoaji

    - name: Create Quarto file
      run: |
        echo "---
        title: 'Test Document'
        output: pdf_document
        ---" > test.qmd
        echo "# Hello, world!\nこれはテストです。" >> test.qmd

    - name: Render Quarto to PDF
      run: |
        quarto render test.qmd
